name = "install"
name_pretty = "Install"
parent = "main"
icon = "󰏖"
fixed_order = true

[[entries]]
text = "AI CLIs"
subtext = ">"
icon = "󱜙"
submenu = "ai-install"

[[entries]]
text = "Browsers"
subtext = ">"
icon = "󰖟"
submenu = "browsers"

[[entries]]
text = "Development Languages"
subtext = ">"
icon = "󰅩"
submenu = "languages"

[[entries]]
text = "JavaScript Tools"
subtext = ">"
icon = "󰛦"
submenu = "javascript-tools"

[[entries]]
text = "Pacman"
icon = "󰏖"
actions = { open = "python3 $HOME/.config/walker/scripts/actions/install/software.py picker-launch pacman" }

[[entries]]
text = "Yay (AUR)"
icon = "󰀦"
actions = { open = "python3 $HOME/.config/walker/scripts/actions/install/software.py picker-launch aur" }
